/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author eduar
 */
public final class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    
    public LogIn() {
        initComponents();
        
    }
    
  
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserInput = new javax.swing.JTextField();
        PassInput = new javax.swing.JPasswordField();
        Username = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        Log = new javax.swing.JButton();
        Register = new javax.swing.JButton();
        In1 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(UserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 170, 40));

        PassInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(PassInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 170, 40));

        Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username.setText("User Name");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, 20));

        pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass.setText("Password");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        Log.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Log.setText("Log In");
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        jPanel1.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        Register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        In1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        In1.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\explosive_48px.png")); // NOI18N
        In1.setText("WELCOME TO BOMB");
        jPanel1.add(In1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check.setText("Show password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement st;
        ResultSet rs;
        
        
        // get the username and password
        String username = UserInput.getText();
        String password = String.valueOf(PassInput.getPassword());
        
        //Create a select query to check if the username and password exists in the DB
        
        String query = "SELECT * FROM `user` WHERE `username` = ? AND `password` = ?";
        
        try {
            st = DBConnection.getConnection().prepareStatement(query);
            
              st.setString(1, username);
              st.setString(2, password);
        
        rs = st.executeQuery();
        
        if(rs.next())
        {
            JOptionPane.showMessageDialog(this, " Hello " +" " +username+ " " +" Welcome to Bomb ");
            LoggedIn form = new LoggedIn();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            UserInput.setText("");
            PassInput.setText("");
            
            // close the event
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"Username and Password is invalid" , "Login Error",2);
            
        }
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
        
        
    }//GEN-LAST:event_LogActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        if(check.isSelected()){
            PassInput.setEchoChar((char)0);
        }
        else {
            PassInput.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        userreg jf6 = new userreg();
        
       jf6.show();
       
       dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel In1;
    private javax.swing.JButton Log;
    private javax.swing.JPasswordField PassInput;
    private javax.swing.JButton Register;
    private javax.swing.JTextField UserInput;
    private javax.swing.JLabel Username;
    private javax.swing.JCheckBox check;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pass;
    // End of variables declaration//GEN-END:variables

    }

    
       
        
        

 
