package javaapplication4;


import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eduar
 */
public class userreg extends javax.swing.JFrame {
    String image_path = null;
    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Frame2
     */
    public userreg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.The content of this method is always
 regenerated by the Form Editor.
     * @param imgPath
     * @param label
     * @param rsc
     */
    
    public void displayImage(String imgPath, JLabel label, char rsc)
    {
        ImageIcon imgIco;
        // check if the image is from the project files
        // if the image is from the resource rsc = 'r'
        // if not you can put any character abcd 123467 .......
        if(rsc == 'r')
        {
            imgIco = new ImageIcon(getClass().getResource(imgPath));
        }
        else
        {
         imgIco = new ImageIcon(imgPath);
        }
        
        Image img = imgIco.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        userinput = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        maile = new javax.swing.JTextField();
        Username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regclick = new javax.swing.JButton();
        phoneinput1 = new javax.swing.JTextField();
        LogIn = new javax.swing.JButton();
        Pass1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        Pass2 = new javax.swing.JPasswordField();
        Password1 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Password2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        path2 = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        secu1 = new javax.swing.JComboBox<>();
        lab = new javax.swing.JLabel();
        Ans1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 205, 46));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Register.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\leaf_100px.png")); // NOI18N
        Register.setText("Register Form");
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 320, 100));

        Fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FnameKeyPressed(evt);
            }
        });
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 30));

        firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstname.setText("Last Name");
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        Lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LnameKeyPressed(evt);
            }
        });
        jPanel1.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 30));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 180, 30));

        userinput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(userinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, 30));

        lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastname.setText("First Name");
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setText("Confirm Password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        email1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email1.setText("Email");
        jPanel1.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        maile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(maile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 180, 30));

        Username1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username1.setText("Username");
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Phone Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, 20));

        regclick.setBackground(new java.awt.Color(51, 153, 255));
        regclick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regclick.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\person_40px.png")); // NOI18N
        regclick.setText("Register");
        regclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regclickActionPerformed(evt);
            }
        });
        jPanel1.add(regclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        phoneinput1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneinput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneinput1ActionPerformed(evt);
            }
        });
        phoneinput1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneinput1KeyTyped(evt);
            }
        });
        jPanel1.add(phoneinput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 30));

        LogIn.setBackground(new java.awt.Color(255, 153, 153));
        LogIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogIn.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\login_48px.png")); // NOI18N
        LogIn.setText("Click here to Log In");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        jPanel1.add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        Pass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 180, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\Female User Update_40px.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\person_40px.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        check.setBackground(new java.awt.Color(204, 204, 255));
        check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check.setText("Show Pass");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, 30));

        Pass2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 180, 30));

        Password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password1.setText("Password");
        jPanel1.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, 20));

        buttonGroup1.add(Male);
        Male.setText("Male");
        jPanel1.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        buttonGroup1.add(Female);
        Female.setText("Female");
        jPanel1.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        Password2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password2.setText("Avatar");
        jPanel1.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, 20));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\ICONSS\\Icon\\image_64px.png")); // NOI18N
        jButton1.setText("Select Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 190, 60));

        path2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        path2.setOpaque(true);
        jPanel1.add(path2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 130, 110));

        sec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sec.setText("Answer");
        jPanel1.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 20));

        secu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "What is the name of your favorite pet?", "What is the year you are born?", "What is your favorite food?", "Who is your favorite artist?", " " }));
        jPanel1.add(secu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 310, 30));

        lab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab.setText("Security Question");
        jPanel1.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 20));

        Ans1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ans1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 180, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Downloads\\6934839-leaves-vector-background.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-840, -250, -1, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/close_sign_30px.png"))); // NOI18N
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/add_user_group_man_man_40px.png"))); // NOI18N
        jMenuItem2.setText("About our team");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_FnameActionPerformed

    private void regclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regclickActionPerformed
        // TODO add your handling code here:
         String firstname = Fname.getText();
         String lastname = Lname.getText();
         String address = Address.getText();
         String username = userinput.getText();
         String email = maile.getText();
         String pass1 = String.valueOf(Pass1.getPassword());
         String pass2 = String.valueOf(Pass2.getPassword());
         String phone = phoneinput1.getText();
         String secque = secu1.getSelectedItem().toString();
         String answer = Ans1.getText();
         String gender = "Male";
     
         
         if(Female.isSelected()){
             gender = "Female";
         }
        
// check if the data are empty
         if(verifyFields())
         {
// check if the username already exists
             if(!checkUsername(username))
             {
                 PreparedStatement ps;
                 ResultSet rs;
                 String registerUserQuery = "INSERT INTO `user`(`fname`, `lname`, `addr`, `gender`, `email`, `phone`, `username`, `password`, `confirmpass`, `Security Question`, `Answer`, `picture`)  "
                         + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
                 
                 try {
                     
                     ps = DBConnection.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, firstname);
                     ps.setString(2, lastname);
                     ps.setString(3, address);
                     ps.setString(4, gender);
                     ps.setString(5, email);
                     ps.setString(6, phone);
                     ps.setString(7, username);
                     ps.setString(8, pass1);
                     ps.setString(9, pass2);
                     ps.setString(10, secque);
                     ps.setString(11, answer);
            
                     
                     try {
                         
                         // save the image as blob in the database
                         if(image_path != null){
                         
                             InputStream image = new FileInputStream(new File(image_path));
                             ps.setBlob(12, image);
                             
                         }else{
                             ps.setNull(12, java.sql.Types.NULL);
                         }
                         
                         if(ps.executeUpdate() != 0){
                             JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                             Fname.setText("");
                             Address.setText("");
                             Lname.setText("");
                             maile.setText("");
                             userinput.setText("");
                             phoneinput1.setText("");
                             Pass1.setText("");
                             Pass2.setText("");
                             
                             
                             
                         }else{
                             JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                             
                         }
                         
                     } catch (FileNotFoundException ex) {
                         Logger.getLogger(userreg.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(userreg.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
             }
         }
                 
                                                                        
      
        
    }//GEN-LAST:event_regclickActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        // TODO add your handling code here:
        LogIn jf5 = new LogIn();
        jf5.show();
        
        dispose();
    }//GEN-LAST:event_LogInActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        if(check.isSelected()) {
            Pass1.setEchoChar((char)0);
            Pass2.setEchoChar((char)0);
        }
        else{
            Pass1.setEchoChar('*');
            Pass2.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    private void phoneinput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneinput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneinput1ActionPerformed

    private void phoneinput1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneinput1KeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
        }
        
    }//GEN-LAST:event_phoneinput1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*images", ".png","jpg",".jpeg");
        filechooser.addChoosableFileFilter(filter);
        
        if(filechooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION)
        {
          File selectedImage = filechooser.getSelectedFile();
          String image_path = selectedImage.getAbsolutePath();
          displayImage(image_path, path2,'a');
          path2.setText(image_path);
          System.out.println(image_path);
        }
        else
        {
            System.out.println("no file selected");
        }
        
                                                           
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ans1ActionPerformed

    private void FnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
         
        if(Character.isLetter(c)|Character.isWhitespace(c)| Character.isISOControl(c)) {
            
            Fname.setEditable(true);
            
        } else {
            Fname.setEditable(false);
        }
    }//GEN-LAST:event_FnameKeyPressed

    private void LnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
         
        if(Character.isLetter(c)|Character.isWhitespace(c)| Character.isISOControl(c)) {
            
            Lname.setEditable(true);
            
        } else {
            Lname.setEditable(false);
        }
    }//GEN-LAST:event_LnameKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
                        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Users\\eduar\\Documents\\NetBeansProjects\\html files\\first.html" );

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Check file details");
        }
        {
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          JFrame frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit",
                "Tic Tac Toe" , JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @return 
     */
       public boolean verifyFields()
    {
        String fname = Fname.getText();
        String uname = userinput.getText();
        String phone = phoneinput1.getText();
        String pass1 = String.valueOf(Pass1.getPassword());
        String pass2 = String.valueOf(Pass2.getPassword());
        String sec1 = secu1.getSelectedItem().toString();
        String ans2 = Ans1.getText();
        
        // check empty fields
        if(fname.trim().equals("") || uname.trim().equals("") || phone.trim().equals("")
           || pass1.trim().equals("") || pass2.trim().equals("")| sec1.trim().equals("")| ans2.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
        }
        
        // check if the two password are equals or not
        else if(!pass1.equals(pass2))
        {
           JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2); 
           return false;
        }
        
        // if everything is ok
        else{
            return true;
        }
    }

    public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `user` WHERE `username` = ?";
        
        try {
            
            st = DBConnection.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(userreg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;
    }
     public boolean checkEmail(String email){
        
        PreparedStatement st;
        ResultSet rs;
        boolean email_exist = false;
        
        String query = "SELECT * FROM `user` WHERE `email` = ?";
        
        try {
            
            st = DBConnection.getConnection().prepareStatement(query);
            st.setString(2, email);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                email_exist = true;
                JOptionPane.showMessageDialog(null, "This Email is Already Taken, Choose Another One", "Email Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(userreg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return email_exist; }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new userreg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Ans1;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JButton LogIn;
    private javax.swing.JRadioButton Male;
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JPasswordField Pass2;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel Password2;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel Username1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField maile;
    private javax.swing.JLabel path2;
    private javax.swing.JTextField phoneinput1;
    private javax.swing.JButton regclick;
    private javax.swing.JLabel sec;
    private javax.swing.JComboBox<String> secu1;
    private javax.swing.JTextField userinput;
    // End of variables declaration//GEN-END:variables
}
