/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eduar
 */
import java.util.Random;
import javax.swing.JOptionPane;


public class OddFrame extends javax.swing.JFrame {

    static int score = 0; // score of each correct question
       static int count = 0; // number of questions
       
       // we need To generate random number
       Random r = new Random();
       int randomNum; 
    /**
     * Creates new form ODDEVEN
     */
    public OddFrame() {
        initComponents();
         randomNum = r.nextInt(100);
         Number3.setText(String.valueOf(randomNum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EVEN1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ODD1 = new javax.swing.JButton();
        Number3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EVEN1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        EVEN1.setText("EVEN");
        EVEN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVEN1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Score");

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Color Changer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ODD1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        ODD1.setText("ODD");
        ODD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ODD1ActionPerformed(evt);
            }
        });

        Number3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ODD1)
                    .addComponent(jLabel2))
                .addGap(78, 78, 78)
                .addComponent(EVEN1)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(318, 318, 318)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(360, 360, 360)
                            .addComponent(Number3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Number3)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ODD1)
                    .addComponent(EVEN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ODD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ODD1ActionPerformed
        // TODO add your handling code here:
        
        // generate numbers but it will ever count to 10 questions
        
        count = count+1;
        int num = Integer.parseInt(Number3.getText());
        if (count == 10) {
            
            if(num%2!=0) {
                score = score+1; // adds score
                Score.setText(String.valueOf(score));
                randomNum = r.nextInt(100);
                
            }else {
                // if not odd
               randomNum = r.nextInt(100);
               Number3.setText(String.valueOf(randomNum));
            }
         JOptionPane.showMessageDialog(this, "Your score is: " +score+ "/10");
         //resetValues 
         count =0;
         score =0;
         Score.setText("");
         randomNum = r.nextInt(100);
         Number3.setText(String.valueOf(randomNum));
         
        } else {  
            if(num%2!=0) {
                score = score+1; // adds score
                Score.setText(String.valueOf(score));
                randomNum = r.nextInt(100);
                Number3.setText(String.valueOf(randomNum));
                
        } else {
                randomNum = r.nextInt(100);
                Number3.setText(String.valueOf(randomNum));
            }
     
        }
        
        
    }//GEN-LAST:event_ODD1ActionPerformed

    private void EVEN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVEN1ActionPerformed
        // TODO add your handling code here:
        count = count+1;
        int num = Integer.parseInt(Number3.getText());
        if (count == 10) {
            
            if(num%2==0) {
                score = score+1; // adds score
                Score.setText(String.valueOf(score));
                randomNum = r.nextInt(100);
                
            }else {
                // if not odd
               randomNum = r.nextInt(100);
               Number3.setText(String.valueOf(randomNum));
            }
         JOptionPane.showMessageDialog(this, "Your score is: " + "/10");
         //resetValues 
         count =0;
         score =0;
         Score.setText("");
         randomNum = r.nextInt(100);
         Number3.setText(String.valueOf(randomNum));
         
        } else {  
            if(num%2==0) {
                score = score+1; // adds score
                Score.setText(String.valueOf(score));
                randomNum = r.nextInt(100);
                Number3.setText(String.valueOf(randomNum));
                
        } else {
                randomNum = r.nextInt(100);
                Number3.setText(String.valueOf(randomNum));
            }
     
        }
        
            
    }//GEN-LAST:event_EVEN1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NewJFrame jf1 = new NewJFrame();   
        jf1.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EVEN1;
    private javax.swing.JLabel Number3;
    private javax.swing.JButton ODD1;
    private javax.swing.JLabel Score;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
